package view;

import controller.MainController;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

public class AuditPanel extends JPanel {
    private MainController control = null;
    private TablesView tableView = null;
    
    public AuditPanel() {
        control = MainController.getInstance();
        initComponents();
        tableView = new TablesView(AuditTable);
        showTable();
        tableView.addIdModel();
        tableView.addListener();
    }

    private Vector columnsName() {
        Vector columnNames = new Vector();     
         columnNames.addElement("Num");
         columnNames.addElement("Name");
         columnNames.addElement("Num DLP");
         columnNames.addElement("Title");
         return columnNames;
    }
    
     private void showTable() {
         tableView.data = control.findRecord(control.textQuery.AUDITCLIENT);
         tableView.fillTable(columnsName());
    }
    
    private void addClient() {
        tableView.addRow();
    }

    private void saveClient() {
       boolean isNew = false;
       for (int i = 0; i < tableView.changeNum.size(); i++) {
           if (tableView.changeNum.get(i) == "") {
                isNew = true;
           }        
       }
       if (isNew)
           control.createRecord(tableView.data, control.textQuery.AUDITCLIENT);
       else 
          control.updateRecord(tableView.changeNum, tableView.data, control.textQuery.AUDITCLIENT);
    }
     
    private void deleteClient() {
        int delNum = (Integer)((Vector)tableView.data.get(AuditTable.getSelectedRow())).get(0);
        control.deleteRecord(delNum, control.textQuery.AUDITCLIENT);
        tableView.deleteRow();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AuditScrollPane = new javax.swing.JScrollPane();
        AuditTable = new javax.swing.JTable();
        AuditLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        NewButton = new javax.swing.JButton();

        AuditTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        AuditScrollPane.setViewportView(AuditTable);

        AuditLabel.setText("Audit");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        NewButton.setText("New");
        NewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AuditLabel)
                    .addComponent(AuditScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveButton)
                .addGap(18, 18, 18)
                .addComponent(DeleteButton)
                .addGap(26, 26, 26)
                .addComponent(NewButton)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(AuditLabel)
                .addGap(18, 18, 18)
                .addComponent(AuditScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(DeleteButton)
                    .addComponent(NewButton))
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButtonActionPerformed
        addClient();
    }//GEN-LAST:event_NewButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        saveClient();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        deleteClient();
    }//GEN-LAST:event_DeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuditLabel;
    private javax.swing.JScrollPane AuditScrollPane;
    private javax.swing.JTable AuditTable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton NewButton;
    private javax.swing.JButton SaveButton;
    // End of variables declaration//GEN-END:variables
}
